[package]
name = "homer-compiler"
version = "0.1.0"
authors = ["Martin Huschenbett <martin.huschenbett@posteo.me>"]
edition = "2018"
publish = false
description = "The compiler for the very boring function programming language Homer."
homepage = "https://github.com/hurryabit/homer#readme"
repository = "https://github.com/hurryabit/homer.git"
license = "Apache 2.0"

[build-dependencies]
lalrpop = { version = "0.19.1", features = ["lexer"] }

[dependencies]
flexi_logger = "0.16.1"
genawaiter = "0.99.1"
im = "15.0.0"
lalrpop-intern = "0.15.1"
lalrpop-util = "0.19.1"
log = "0.4.11"
lsp-server = "0.5.0"
lsp-types = "0.83.1"
regex = "1.4.2"
serde = "1.0.117"
serde_json = "1.0.59"

[dev-dependencies]
insta = "1.2.0"
